name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build, Login and Push
      run: |
        IMAGE="harbor.kakor.ovh/ipim2il/groupe-6/samuel-alexandre:$(date +%s)"
        docker build . --file Dockerfile --tag $IMAGE
        docker login harbor.kakor.ovh -u ipi -p B4teau123!
        docker push $IMAGE

    - name: Install OpenShift CLI
      uses: redhat-actions/oc-installer@v1

    - name: Connect to OpenShift
      run: oc login --token=${{ secrets.OKD_TOKEN }} --server=https://api.openshift.kakor.ovh:6443 --insecure-skip-tls-verify=true