name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install OpenShift
      uses: redhat-actions/oc-installer@v1

    - name: Connect
      run: oc login --token=${{ secrets.OKD_TOKEN }} --server=https://api.openshift.kakor.ovh:6443

    - uses: actions/checkout@v4

    - name: Build and Push Docker image
      run: |
        IMAGE="harbor.kakor.ovh/ipim2il/groupe-6-samuel-alexandre:$(date +%s)"
        docker build . --file Dockerfile --tag $IMAGE
        docker push $IMAGE
